- name: Install K3s with Public IP TLS SAN
  hosts: localhost
  become: yes
  gather_facts: yes

  vars:
    k3s_version: "latest"

  tasks:
    - name: Get public IP of EC2
      shell: curl -s ifconfig.me
      register: public_ip

    - name: Install dependencies
      apt:
        name:
          - curl
        state: present
        update_cache: yes

    - name: Install K3s with public IP TLS SAN
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san {{ public_ip.stdout }}" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s service to start
      shell: sleep 10

    - name: Verify k3s installation
      shell: kubectl get nodes
      register: node_check
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      ignore_errors: yes

    - name: Show node status
      debug:
        var: node_check.stdout

